openapi: 3.0.0
info:
  title: OPAG-CAMARA Traffic Influence API
  description: |
    The reference scenario foresees a Service provided by many Application Server instances deployed in different geographical location (Edge sites). 
    The Traffic Influence API provides the capability to establish the best connectivity, in a specific geographical area, between the User Equipment (UE), e.g. the user’s smartphone, and the optimal Application Server instance (EAS: Edge Application Server) nearby. 
    The API provides the best network quality at the Edge, establishing the fastest routing between UE and the closest EAS instance, in a specific geographical location, for a specific set of user and in a certain period of time. Considering a Service with many EASs distributed geographically, if the user (the UE) moves to another geographical area, the API can be invoked to set the network providing a new faster routing towards another EAS instance located closer to the new edge location. 
    The Service architecture foresees one or more EASs and a component, the Application Function (AF), that is the API consumer. Invoking the TI API, the AF can create a Traffic Influence resource specifying the desired request. 
    The TI API provider implements the intent specified in the Traffic Influence resource.
  termsOfService: http://swagger.io/terms/
  contact:
    email: project-email@sample.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
externalDocs:
  description: Product documentation at Camara
  url: https://github.com/camaraproject/
#security:
#  - oAuth2ClientCredentials: []
servers:
  - url: "{apiRoot}/{basePath}"
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root
      basePath:
        default: ti/v0
        description: Base path for the Traffic Influence API


paths:
  /traffic-influences:
    get:
      tags:
        - TrafficInfluence API GET Operation
      summary: Retries existing TrafficInfluence Resources
      description: Reads all of the active trafficinfluence resources owned by the AF
      operationId: GetTrafficInfluences
      responses:
        '200':
          description: Contains information about existing TrafficInfluences. 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TrafficInfluence"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        '500':
          $ref: "#/components/responses/GenericError"
        "503":
          $ref: "#/components/responses/Generic503"
        '504':
          $ref: "#/components/responses/BackendConnTimeout"
          
    post:
      tags:
        - TrafficInfluence API POST Operation
      summary: Creates a new TrafficInfluence Resource
      description: Creates a new TrafficInfluence Resource
      operationId: PostTrafficInfluence
      requestBody:
        description: Describes the request body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrafficInfluence'

      responses:
        '201':
          description: Created (Successful creation of subscription)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrafficInfluence'
#          headers:
#            Location:
#              description: 'Contains the URI of the newly created resource'
#              required: true
#              schema:
#                type: string
        '500':
          $ref: '#/components/responses/GenericError'
        '504':
          $ref: '#/components/responses/BackendConnTimeout'
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "503":
          $ref: "#/components/responses/Generic503"

  /traffic-influences/{TIResource_id}:
    parameters:
      - name: TIResource_id
        in: path
        description: Identifier of the specific trafficinfluence resource to be retrieved, modified or deleted
        required: true
        schema:
          type: string
    get:
      summary: read the specific trafficinfluence resource
      tags:
        - TrafficInfluence API GET Operation
      responses:
        '200':
          description: OK. 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrafficInfluence'
        '404':
          $ref: '#/components/responses/ResNotFound'
        '500':
          $ref: '#/components/responses/GenericError'
        '504':
          $ref: '#/components/responses/BackendConnTimeout'
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "503":
          $ref: "#/components/responses/Generic503"
    delete:
      summary: Delete an existing trafficinfluence resource
      tags:
        - TrafficInfluence API Delete Operation
      responses:
        '200':
          $ref: '#/components/responses/OkDeleted'
        '404':
          $ref: '#/components/responses/ResNotFound'
        '504':
          $ref: '#/components/responses/BackendConnTimeout'
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "503":
          $ref: "#/components/responses/Generic503"
          
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      # description: APIKEY APIGEE
      in: header
      name: apikey
  schemas: 
    TrafficInfluence:
      type: object
      properties:
        trafficInfluenceID:
          type: array
          items:
            type: string
          minItems: 1
          description: Defines the local breakout required for the particular Telco Edge Node and Service Edge Node. I.E. TurinEast, TurinNorth
          # FIXME siccome stiamo usando GET e POST sulla stessa risorsa va in required o no?
        mobileNumbers:
          description: Group of users for which the local breakout should be applied defined by their MSISDN (the SIM number).
          type: array
          items:
            $ref: '#/components/schemas/MobileNumber'
          minItems: 1
        trafficFilters:
          type: array
          items:
            $ref: '#/components/schemas/FlowInfo'
          minItems: 1
          description: Identifies IP packet filters. To be used when a the Application needs a traffic flow towards a specific EAS instance 
        temporalValidities:
          type: array
          items:
            $ref: '#/components/schemas/TemporalValidity'
          minItems: 1
        geoAreas:
          #FIXME required true in alternative
          description: Identifies the geographical areas where the Application Service will be delivered. The serving EAS instance whould be as close as possibile.
          type: array
          items:
            $ref: '#/components/schemas/GeographicalArea'
        easId:
          #FIXME required true in alternative
          type: string
          example: "Virtual_Reality_Arena"
          description: Identifies a specific EAS instance towards routing the traffic flow from the UE
      required:
        - easId
        - geoAreas
    MobileNumber:
      description: Identifies MSISDN
      type: string
      
    GeographicalArea:
      type: object
      properties:
        civicAddress:
          type: object
        shapes:
          $ref: '#/components/schemas/GeographicArea'
    FlowInfo:
      type: object
      properties:
        flowId:
          type: integer
          description: Indicates the IP flow.
        flowDescriptions:
          type: array
          items:
            type: string
          description: Indicates the packet filters of the IP flow. 
          minItems: 1
          maxItems: 2
      required:
        - flowId
    TemporalValidity:
      description: Indicates the time interval(s) during which the Local Breakout request is to be applied
      type: object
      properties:
        startTime:
          $ref: '#/components/schemas/DateTime'
        stopTime:
          $ref: '#/components/schemas/DateTime'
    GeographicArea:
      # To be completed: this object must be further defined. First it is better to agree on using the 3GPP object type or maybe choosing something else, e.g. from Google maps. Once decided, we can continue with the object definition.
      description: Geographic area specified by different shape.
#      anyOf:
#        - $ref: '#/components/schemas/Point'
#        - $ref: '#/components/schemas/PointUncertaintyCircle'
#        - $ref: '#/components/schemas/PointUncertaintyEllipse'
#        - $ref: '#/components/schemas/Polygon'
#        - $ref: '#/components/schemas/PointAltitude'
#        - $ref: '#/components/schemas/PointAltitudeUncertainty'
#        - $ref: '#/components/schemas/EllipsoidArc'
    DateTime:
      format: date-time
      type: string

    ErrResponse:
      type: object
      properties:
        status:
          type: string
          example: OK
        message:
          type: string
          example: OK
    ErrorInfo:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Code given to this error
        message:
          type: string
          description: Detailed error description
  responses:
    ResNotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrResponse'
          example:
            status: ERROR
            message: Resource not found
    GenericError:
      description: An unknow error has occurred
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrResponse'
          example:
            status: ERROR
            message: Generic error
    BackendConnTimeout:
      description: Connection timeout towards backend service has occurred
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrResponse'
          example:
            status: ERROR
            message: Backend connection timeout
    OkDeleted:
      description: The resource has been successfully deleted
      content:
        application/json:
          example:
            status: OK
            message: Deleted
    Generic400:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: INVALID_INPUT
            message: "Schema validation failed at  ..."
    Generic401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: UNAUTHORIZED
            message: "Authorization failed: ..."
    Generic403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: FORBIDDEN
            message: "Operation not allowed: ..."
    SessionNotFound404:
      description: Session not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: NOT_FOUND
            message: "Session Id does not exist"
    Generic503:
      description: Service unavailable
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: SERVICE_UNAVALIBLE
            message: "Service unavailable"